# Generated by Django 5.2.5 on 2025-11-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteerapplication',
            options={'ordering': ['-applied_at']},
        ),
        migrations.AddField(
            model_name='volunteerapplication',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
