# Generated by Django 5.2.5 on 2025-11-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('ngo', 'NGO/Organization'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
