# Generated by Django 5.2.5 on 2025-11-19 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crisis', '0002_alter_crisispost_options_crisispost_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('donor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('item_description', models.TextField(help_text="Describe items: e.g., '10 blankets, 5kg rice, 20 bottles water'")),
                ('quantity', models.CharField(blank=True, help_text='Optional: Total items count', max_length=100, null=True)),
                ('delivery_method', models.CharField(blank=True, help_text="How will you deliver? e.g., 'Self-delivery', 'Courier'", max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('crisis_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_donations', to='crisis.crisispost')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Donation Goods',
                'ordering': ['-donated_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('donor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('donor_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('other', 'Other')], default='bkash', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('donated_at', models.DateTimeField(auto_now_add=True)),
                ('crisis_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_donations', to='crisis.crisispost')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-donated_at'],
            },
        ),
    ]
